### ISSUE TITLE
Fix impl module

### ISSUE THREAD

**Issue by marschall** [javaee/jsonp#42] opened 2017-05-12 05:34 UTC
The impl module exports `javax.json` and`javax.json.stream`. IMO the impl module should export `org.glassfish.json.api` and require the module `java.json`.

Also the name of the impl module is `org.glassfish.java.json` but the package is `org.glassfish.json.api`. Stephen Colebourne has [argued](http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) that the module name should be the same as the name of the super-package.

Ideally you have a Java 9 build with a module path to make sure everything works.

**Comment by keilw** [comment] 2017-05-23 00:26
As https://github.com/javaee/jsonp/issues/43 was closed, is there a need to keep this one open?

**Comment by marschall** [comment] 2017-05-23 05:35
Yes IMO this should be kept open. I don't see how the implementation module as is works. As I said, as far as I can see the `requires` and `export` directives look wrong to me. This is independent of the name.
The project doesn't build right now so I can't verify this but the errors I get from IntelliJ seem to confirm this. As I said, and automated with Java 9 and a module path would clear all of this up.
If you can tell me how you verified the module declaration then I can try to verify this.

**Comment by lukasj** [comment] 2017-05-23 07:39
> The project doesn't build right now
Which JDK, which mvn, what mvn args are you passing in, what do you expect and what do you get?
```bash
griffin-lj:jsonp lukas$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

griffin-lj:jsonp lukas$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+169)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+169, mixed mode)

griffin-lj:jsonp lukas$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /Users/lukas/java/apache-maven-3.5.0
Java version: 9-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

griffin-lj:jsonp lukas$ echo $MAVEN_OPTS
--add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED -Xmx4g

griffin-lj:jsonp lukas$ mvn -U -C clean install -Dnon.final=true
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JSR 374 (JSON Processing) RI ....................... SUCCESS [  0.705 s]
[INFO] JSR 374 (JSON Processing) API ...................... SUCCESS [  7.765 s]
[INFO] JSR 374 (JSON Processing) Default Provider ......... SUCCESS [  6.964 s]
[INFO] JSR 374 (JSON Processing) Media for JAX-RS ......... SUCCESS [  2.542 s]
[INFO] JSR 374 (JSON Processing) Media for JAX-RS 1.1 ..... SUCCESS [  2.391 s]
[INFO] JSR 374 (JSON Processing) Tests .................... SUCCESS [ 27.192 s]
[INFO] providers .......................................... SUCCESS [  0.014 s]
[INFO] customprovider ..................................... SUCCESS [  0.705 s]
[INFO] defaultprovider .................................... SUCCESS [  0.153 s]
[INFO] demos .............................................. SUCCESS [  0.012 s]
[INFO] jsondemos-jaxrs .................................... SUCCESS [  0.265 s]
[INFO] jsondemos-twitter .................................. SUCCESS [  0.597 s]
[INFO] jsondemos-facebook ................................. SUCCESS [  0.174 s]
[INFO] jsondemos-jsonpointer .............................. SUCCESS [  0.153 s]
[INFO] jsondemos-servlet .................................. SUCCESS [  0.213 s]
[INFO] JSR 374 (JSON Processing) bundles .................. SUCCESS [  0.031 s]
[INFO] RI bundle .......................................... SUCCESS [  0.358 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.213 s
[INFO] Finished at: 2017-05-23T09:28:55+02:00
[INFO] Final Memory: 37M/125M
[INFO] ------------------------------------------------------------------------

griffin-lj:jsonp lukas$ mvn -f demos/jsonpointer/pom.xml exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building jsondemos-jsonpointer 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ jsondemos-jsonpointer ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.114 s
[INFO] Finished at: 2017-05-23T09:34:41+02:00
[INFO] Final Memory: 9M/31M
[INFO] ------------------------------------------------------------------------
```

What am I doing wrong?

**Comment by keilw** [comment] 2017-05-23 09:04
Ideally like https://github.com/javaee-security-spec/soteria (soon to be transferred onto JavaEE, too) the impl should have a CI server like Travis, etc. (if Oracle decided to do this for Glassfish and all related JSRs using a particular one) and if it works on the CI server, that'd be enough IMO.

**Comment by lukasj** [comment] 2017-05-23 11:25
well, it works on my CI server (hudson) for JDK8/JDK9. The fact one does not see it does not mean it does not exist, it may just not be public ;-) that's also the reason I'm trying to get more details about build error.

**Comment by marschall** [comment] 2017-05-23 17:28
adding `-Dnon.final=true` and disabling all the jigsaw stuff for GlassFish fixes the build for me.

I still believe the implementation module should look something like this instead

```java
module org.glassfish.java.json {
    requires java.json;
    exports org.glassfish.json.api;
    uses javax.json.spi.JsonProvider;
}
```

**Comment by lukasj** [comment] 2017-05-23 20:08
It's already documented for some time through https://github.com/javaee/jsonp/blob/master/README.md which makes required info visible directly on the project home page at: https://github.com/javaee/jsonp. One may only have to scroll a bit depending on the screen/monitor resolution. Isn't that sufficient? Is there any more prominent place for this info?

The thing here is, if you've checked the content of the ri module, you noticed that, that it contains API together with implementation, which is currently 'as designed'. Having 'requires' here would lead to split package problem on JDK9. 

Btw: what do you mean by 'disabling all the jigsaw stuff for GlassFish'?

**Comment by marschall** [comment] 2017-05-24 05:31
> Isn't that sufficient?

Yes it is. I don't know how I missed that.

> The thing here is, if you've checked the content of the ri module, you noticed that, that it contains API together with implementation, which is currently 'as designed'.

I missed the dependency plugin.

> which is currently 'as designed'.

What lead to this decision? Was that already the case in 1.0? Doesn't that lead to a lot of conflicts with Jigsaw as an application can not have the both modules present at the same time? I would expect library to depend on `java.json` only. Once somebody depends on `org.glassfish.java.json` e.g. for tests you get a conflict because you have to modules exporting the same packages.

> Having 'requires' here would lead to split package problem on JDK9.

That's correct. However the `export` for `org.glassfish.json.api` is still missing. We are currently using this and it is our understanding that implementing a `BufferPool` is API and supported. We would like to be able to continue using this.

> Btw: what do you mean by 'disabling all the jigsaw stuff for GlassFish'?

```
--add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED
```

**Comment by keilw** [comment] 2017-05-24 09:16
So is there something to document similar to the README file, or a code change?

**Comment by lukasj** [comment] 2017-05-24 23:45
I agree that 

> the export for org.glassfish.json.api is still missing

good point and fixed. Workaround for the time being is using `--add-exports org.glassfish.java.json/org.glassfish.json.api=<target-module>`

wrt 'as designed': yes it was the same in 1.0. At this point JDK 9 is still not finalized and JSR #376 has not been approved yet, so it is not easy to predict how exactly it is going to work with final JDK 9 release. What one has now is:
* java.json module - API only module, no implementation available
* org.glassfish.java.json module - a bundle of API and RI. RI here works as a `default implementation` which will be used if and only if there is no other JSON-P provider found on the classpath/modulepath. I created and pushed simple example how this is expected to work, see d9a619b0c731b9872d2f826c04e5cdf60f61f0d3

I'd say it's up to the user and particular use-case whether default implementation is wanted/required or not. Ie JDK team requires each API to include default implementation as a fallback (I know, this is not part if JDK...)

BTW: While preparing this example I noticed that `ServiceLoader` definition on JDK 9 conflicts with `JsonProvider.provider()` method - basically the problem is that ServiceLoader will call `provider()` method on the service implementation extending `JsonProvider`, which unless explicitly overridden is inherited from `JsonProvider.provider()`, so in the end there is infinite cycle.

wrt 'jigsaw stuff for GlassFish': https://issues.apache.org/jira/browse/MWAR-397 has, IMHO, nothing to do with GlassFish apart from war packaging which is not GF specific. That is what confused me...

**Comment by lukasj** [comment] 2017-05-30 07:36
* build property is documented
* missing export has been added
* sample showing the way it is supposed to work has been added
* JDK bug for the 'provider' behaviour has been filed as well: https://bugs.openjdk.java.net/browse/JDK-8181204

there seems to be nothing more to do here, so closing

**Closed by lukasj** 2017-05-30 07:36 UTC

**Comment by marschall** [comment] 2017-05-30 08:05
Jigsaw is supposed to ship in two months so I don't see how any big changes can happen.

Consider the following scenario:
- Application A has a dependency on a third party library L which depends on the `java.json` module. I think this is reasonable to expect third party libraries to depend on the API only and not the implementation.
- Application A decides to use the RI as the implementation for JSONP and therefore adds a dependency on `org.glassfish.java.json`

This will not work because there are now two modules, `java.json` and `org.glassfish.java.json` exporting the same package. The application simply won't start. This example probably could be made to run in theory with ClassLoader isolation. However as Jigsaw is supposed to ship in two months I don't think this is going to happen. But even then the following scenario won't work:

- Application A has a component C1 which dependency on a third party library L which depends on the `java.json` module. The library returns a JSONP type in one of it's public interfaces. Component C1 also returns a JSONP type in one of it's public interfaces.
- Application A also has a component C2 which depends on component C1 and `org.glassfish.java.json`.

At this point ClassLoader isolation will no longer work. This would require a complete redesign which is extremely unlikely.

**Comment by keilw** [comment] 2017-05-30 12:30
In any case, the Umbrella Java EE Spec Lead(s) were clear, that no official support for Jigsaw by Java EE is intended at this point. If a large demand arises, I'm sure, individual JSRs or EE as a whole could bring out a MR to address this. Otherwise it is for Java EE 9.
